version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]

